-keep class com.acszo.redomi.model.Providers { *; }
-keep class com.acszo.redomi.model.Link { *; }
-keep class com.acszo.redomi.model.SongInfo { *; }
-keep class com.acszo.redomi.model.Release { *; }
-keep class com.acszo.redomi.model.Asset { *; }